### ISSUE TITLE
服务器是不是挂了。

### ISSUE THREAD

**Issue by boloboloda** [trazyn/JJJkkk#11]
先说一句大佬🐂🍺。
我看issues都很久了。
我翻出去也没有内容。
不知道现在服务器有没有问题。

**Comment by trazyn** [comment]
服务器上线了

**Comment by boloboloda** [comment]
感谢您的回复。

- 设备：iPhoneXR
- 系统：iOS12.1.4

现在还存在之前的问题。
不翻墙会请求超时。
翻墙会出现network error的错误。
是不是我这边的问题。

**Comment by trazyn** [comment]
服务器确实被墙了，国内目前不能访问
