### ISSUE TITLE
启动错误

### ISSUE THREAD

**Issue by ghost** [trazyn/JJJkkk#12]
localdeMacBook-Pro:JJJkkk local$ yarn run ios
yarn run v1.16.0
$ react-native run-ios
Scanning folders for symlinks in /Users/local/JJJkkk/node_modules (11ms)
Found Xcode project JJJkkk.xcodeproj

Could not find iPhone 6 simulator

**Comment by ghost** [comment]
10.14.3
Xcode 11

**Comment by houbaron** [comment]
@marsman233 
https://github.com/facebook/react-native/issues/23282#issuecomment-476439080
