### ISSUE TITLE
network error

### ISSUE THREAD

**Issue by zhaoqt521** [trazyn/JJJkkk#3]
![img_458f2dec3f7f-1](https://user-images.githubusercontent.com/16076705/38081975-f5348ba6-3377-11e8-99dc-1001611740e3.jpeg)
![img_63e227916d76-1](https://user-images.githubusercontent.com/16076705/38082004-06b81e60-3378-11e8-92b4-845c475222c7.jpeg)

**Comment by trazyn** [comment]
服务器挂了，现在好了

**Comment by yangbryant** [comment]
![png -a7eb6027797a-1](https://user-images.githubusercontent.com/8056564/40529833-11d522b0-6029-11e8-9653-d8452ec9665e.png)

**Comment by trazyn** [comment]
@yangbryant 垃圾服务器挂逼了重启了
